
-- Drop existing tables if they exist (Local Development Reset)
-- DROP TABLE IF EXISTS posts CASCADE;
-- DROP TABLE IF EXISTS users CASCADE;

-- Initialize the database with a users table
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    age INTEGER NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (id, name, age, email, phone) VALUES
    (1,  'John Doe', 25, 'john.doe@example.com','123-456-7890'),
    (2,  'Jane Smith', 30, 'jane.smith@example.com','098-765-4321'),
    (3,  'Bob Johnson', 35, 'bob.johnson@example.com','555-123-4567'),
    (4,  'Alice Brown', 28, 'alice.brown@example.com','404-222-1133'),
    (5,  'Michael Davis', 40, 'michael.davis@example.com','312-654-9090'),
    (6,  'Sophia Wilson', 26, 'sophia.wilson@example.com','213-987-6543'),
    (7,  'Ethan Miller', 33, 'ethan.miller@example.com','619-890-1122'),
    (8,  'Olivia Martinez', 29, 'olivia.martinez@example.com','702-321-7788'),
    (9,  'William Garcia', 27, 'william.garcia@example.com','646-765-2222'),
    (10, 'Ava Robinson', 24, 'ava.robinson@example.com','415-600-9080'),
    (11, 'Liam Anderson', 38, 'liam.anderson@example.com','202-555-7822'),
    (12, 'Emily Thompson', 32, 'emily.thompson@example.com','303-420-5588'),
    (13, 'Daniel White', 45, 'daniel.white@example.com','512-990-3344'),
    (14, 'Grace Clark', 22, 'grace.clark@example.com','617-303-4400'),
    (15, 'Noah Lewis', 31, 'noah.lewis@example.com','929-100-8899'),
    (16, 'Isabella Harris', 29, 'isabella.harris@testmail.com','714-555-2233'),
    (17, 'James Taylor', 36, 'james.taylor@demo.org','818-777-4455'),
    (18, 'Charlotte Young', 23, 'charlotte.young@mail.net','510-888-6677'),
    (19, 'Benjamin King', 42, 'benjamin.king@sample.io','650-999-1122'),
    (20, 'Mia Wright', 27, 'mia.wright@example.co.uk','206-222-3344'),
    (21, 'Lucas Scott', 34, 'lucas.scott@testdomain.com','503-444-5566')
ON CONFLICT (email) DO NOTHING;


CREATE TABLE IF NOT EXISTS posts (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'posts' AND column_name = 'user_id') THEN
        ALTER TABLE posts ADD COLUMN user_id INTEGER NOT NULL DEFAULT 1 REFERENCES users(id) ON DELETE CASCADE;
    END IF;
END $$;

INSERT INTO posts (id, user_id, title, created_at, updated_at) VALUES
    -- Posts by User with user_id: 1)
    (1, 1, 'Getting Started with Rust', '2025-01-01 10:00:00', '2025-01-01 10:00:00'),
    (2, 1, 'Understanding Ownership', '2025-01-02 14:30:00', '2025-01-02 14:30:00'),
    (3, 1, 'Building Web APIs', '2025-01-03 09:15:00', '2025-01-03 09:15:00'),
    
    -- Posts by User with user_id: 2)
    (4, 2, 'GraphQL vs REST', '2025-01-01 16:20:00', '2025-01-01 16:20:00'),
    (5, 2, 'Database Design Patterns', '2025-01-02 11:45:00', '2025-01-02 11:45:00'),
    (6, 2, 'Frontend State Management', '2025-01-04 13:10:00', '2025-01-04 13:10:00'),
    
    -- Posts by User with user_id: 4)
    (7, 4, 'Docker Containerization', '2025-01-01 08:30:00', '2025-01-01 08:30:00'),
    (8, 4, 'Kubernetes Deployment', '2025-01-03 15:45:00', '2025-01-03 15:45:00'),
    (9, 4, 'CI/CD Best Practices', '2025-01-05 10:20:00', '2025-01-05 10:20:00'),
    (10, 4, 'Monitoring and Observability', '2025-01-06 12:00:00', '2025-01-06 12:00:00')
ON CONFLICT (id) DO NOTHING;


-- Add content column for post body text
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'posts' AND column_name = 'content'
    ) THEN
        ALTER TABLE posts ADD COLUMN content TEXT;
    END IF;
END $$;

-- Create indexes for performance optimization
CREATE INDEX IF NOT EXISTS idx_users_name ON users (LOWER(name));
CREATE INDEX IF NOT EXISTS idx_users_email ON users (LOWER(email));
CREATE INDEX IF NOT EXISTS idx_users_phone ON users (phone);
CREATE INDEX IF NOT EXISTS idx_posts_title ON posts (LOWER(title));
CREATE INDEX IF NOT EXISTS idx_posts_content ON posts USING GIN (to_tsvector('english', content));
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON posts (created_at DESC);

-- Automatically maintain updated_at column on users and posts table
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = CURRENT_TIMESTAMP; RETURN NEW; END; $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_users_updated_at ON users;
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS update_posts_updated_at ON posts;
CREATE TRIGGER update_posts_updated_at BEFORE UPDATE ON posts
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Insert posts with content
INSERT INTO posts (id, user_id, title, content, created_at, updated_at) VALUES
    (11, 5, 'Docker Containerization', 'Docker containers package up code and all its dependencies so the application runs quickly and reliably from one computing environment to another.', '2025-01-01 08:30:00', '2025-01-01 08:30:00'),
    (12, 7, 'Kubernetes Deployment', NULL, '2025-01-03 15:45:00', '2025-01-03 15:45:00'),
    (13, 5, 'CI/CD Best Practices', 'Continuous Integration and Continuous Deployment are essential practices for modern software development. This post covers best practices for setting up robust CI/CD pipelines.', '2025-01-05 10:20:00', '2025-01-05 10:20:00'),
    (14, 7, 'Monitoring and Observability', 'Observability is about understanding your system from the outside, by asking questions about its behavior without knowing its inner workings.', '2025-01-06 12:00:00', '2025-01-06 12:00:00'),
    
    -- Additional posts with varied content
    (15, 5, 'Microservices Architecture', 'Microservices architecture is a method of developing software systems that tries to focus on building single-function modules with well-defined interfaces and operations.', '2025-01-07 10:00:00', '2025-01-07 10:00:00'),
    (16, 6, 'React Performance Optimization', NULL, '2025-01-08 11:30:00', '2025-01-08 11:30:00'),
    (17, 7, 'TypeScript Advanced Types', 'TypeScript provides advanced type features including union types, intersection types, mapped types, and conditional types that help build robust applications.', '2025-01-09 14:20:00', '2025-01-09 14:20:00'),
    (18, 8, 'Testing Strategies', NULL, '2025-01-10 09:15:00', '2025-01-10 09:15:00'),
    (19, 9, 'Serverless Computing', 'Serverless computing allows you to build and run applications without thinking about servers. AWS Lambda, Azure Functions, and Google Cloud Functions are popular options.', '2025-01-11 16:45:00', '2025-01-11 16:45:00'),
    (20, 10, 'API Security Best Practices', 'Securing APIs is crucial in today''s world. Learn about authentication, authorization, rate limiting, and input validation.', '2025-01-12 13:00:00', '2025-01-12 13:00:00'),
    (21, 11, 'Database Indexing', NULL, '2025-01-13 10:30:00', '2025-01-13 10:30:00'),
    (22, 12, 'Async Programming Patterns', 'Asynchronous programming allows your application to handle multiple operations concurrently, improving performance and user experience.', '2025-01-14 15:20:00', '2025-01-14 15:20:00'),
    (23, 13, 'Code Review Guidelines', NULL, '2025-01-15 11:00:00', '2025-01-15 11:00:00'),
    (24, 14, 'Clean Code Principles', 'Writing clean code is an art that requires practice and understanding of fundamental principles. This post covers SOLID principles and code smells.', '2025-01-16 09:45:00', '2025-01-16 09:45:00'),
    (25, 15, 'Agile Development', 'Agile methodology emphasizes iterative development, collaboration, and responding to change. Learn about Scrum, Kanban, and other frameworks.', '2025-01-17 14:00:00', '2025-01-17 14:00:00'),
    (26, 16, 'DevOps Culture', NULL, '2025-01-18 10:15:00', '2025-01-18 10:15:00'),
    (27, 17, 'WebAssembly Fundamentals', 'WebAssembly is a binary instruction format for a stack-based virtual machine. It enables high-performance applications on the web.', '2025-01-19 16:30:00', '2025-01-19 16:30:00'),
    (28, 18, 'Design Patterns in JavaScript', NULL, '2025-01-20 12:00:00', '2025-01-20 12:00:00'),
    (29, 19, 'Cloud Native Applications', 'Cloud-native applications are designed to leverage cloud computing capabilities including scalability, resilience, and distributed architecture.', '2025-01-21 13:45:00', '2025-01-21 13:45:00')
ON CONFLICT (id) DO NOTHING;


-- Reset ID sequence after inserting initial posts
SELECT setval('posts_id_seq', COALESCE((SELECT MAX(id) FROM posts), 1));